### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by chaoming0625** [OscarcarLi/Noise-Reuse-Evolution-Strategies#1]

**Comment by OscarcarLi** [comment]
Thanks for the interest and sorry for the delay! I'll guarantee to release the code some time in the next week.

**Comment by chaoming0625** [comment]
So many thanks.

**Comment by OscarcarLi** [comment]
Hi Chaoming @chaoming0625! The code is now released. Thanks for your interest again and please let us know if you have any questions.
